Dashboard: Add chroma-js types
Dashboard previously failed to compile because of missing types for
chroma-js giving a TypeScript error TS7016. Adding the missing types for
chroma-js removes this error.