Dashboard: Add null handling
After turning strictNullChecks back on one has to explicitly take care
of null in types. Add null handling:

1. Fix TypeScript error TS2345:

TypeScript error in dashboard/src/components/RegionSelector.tsx(25,39):
Argument of type 'null' is not assignable to parameter of type 'string'.
TS2345

    23 |                 props.onRegionChanged(item.value, item.label);
    24 |             } else {
  > 25 |                 props.onRegionChanged(null, null);
       |                                       ^
    26 |             }
    27 |         }
    28 |     }

Fix the above error by changing from
onRegionChanged?: (regionId: RegionId, name: string) => void;
to
onRegionChanged?: (regionId: RegionId|null, name: string|null) => void;
in RegionSelector.tsx.

2. Fix TypeScript error TS2532:

TypeScript error in dashboard/src/components/RegionSelector.tsx(29,21):
Object is possibly 'undefined'.  TS2532

    27 |         }
    28 |     }
  > 29 |     const options = props.regions.map(([id, name]) =>
       |                     ^    ({ value: id, label: name }));
    30 |     const defaultValue = options[0];
    31 |     return (<Select
    32 |         className="region-selector"

Fix the above error by wrapping the
const options = <...>;
with
const options = props.regions ? <...> : [];

3. Fix TypeScript error TS2769:

TypeScript error in dashboard/src/components/RegionSelector.tsx(37,9):
No overload matches this call.
...
    Type 'null' is not assignable to type 'Item'.
...
    35 |         defaultValue={defaultValue}
    36 |         options={options}
  > 37 |         onChange={handleItemChange}
       |         ^
    38 |         isClearable={true}
    39 |         placeholder="Valitse alue..."
    40 |       />);

Fix the above error by changing
const handleItemChange = (item: Item) => {
to
const handleItemChange = (item: Item|null) => {
in RegionSelector.tsx.

4. Fix TypeScript error TS2722:

TypeScript error in dashboard/src/components/TimeSelect.tsx(64,17):
Cannot invoke an object which is possibly 'undefined'.  TS2722

    62 |if (currentTime != null && moment.isMoment(currentTime)) {
    63 |    const newTime = currentTime.clone().add(minutes, 'minutes');
  > 64 |    this.props.onChange(newTime);
       |    ^
    65 |}

Fix the above error by changing the
this.props.onChange(newTime);
into
if (this.props.onChange) {
    this.props.onChange(newTime);
}
in TimeSelect.tsx.

5. Fix TypeScript error TS2322:

TypeScript error in dashboard/src/containers/Dashboard.tsx(47,7):
Type 'Timeout' is not assignable to type 'null'.  TS2322

    45 |    return; // Was already enabled
    46 |  }
  > 47 |  this.timer = setInterval(this.autoUpdate, this.timerInterval);
       |  ^
    48 |}

Fix the above error by changing
timer = null;
to
timer: NodeJS.Timeout|null = null;
in Dashboard.tsx.